spring:
  application:
    name: '@project.name@'
  profiles:
    active: local

---

spring:
  profiles: local
  data:
    cassandra:
      contact-points:
        - localhost
      keyspace-name: sample_keyspace
      port: 9042

server:
  port: 8081
  servlet:
    context-path: /sample-reactive

logging:
  pattern:
  level:
    root: INFO